SELECT *
FROM ot_uploads_tbl A
WHERE
A.EFFDT=(SELECT MAX(B.EFFDT) FROM ot_uploads_tbl B WHERE A.BUCKET_UUID=B.BUCKET_UUID AND A.PROJECT_ID=B.PROJECT_ID)AND
A.EFFSEQ=(SELECT MAX(B.EFFSEQ) FROM ot_uploads_tbl B WHERE A.BUCKET_UUID=B.BUCKET_UUID AND A.PROJECT_ID=B.PROJECT_ID AND A.EFFDT =B.EFFDT)
AND BUCKET_UUID = '13d175c00706';
 
SELECT * FROM OS_EIB_UPLOAD_TEMPLATE WHERE PROJECT_ID='2000297'  ORDER BY UPLOADED_DTM DESC;--10021808	31a8fe4bb643
SELECT * FROM OS_EIB_UPLOAD_TEMPLATE WHERE PROJECT_ID='2000294' AND BUCKET_UUID='31a8fe4bb643' AND ROWNO='2' ORDER BY UPLOADED_DTM DESC;
SELECT DISTINCT BUCKET_UUID,TABLE_NAME FROM OS_EIB_UPLOAD_TEMPLATE WHERE PROJECT_ID='2000288';

SELECT *
FROM ot_uploads_tbl A ORDER BY EFFDT DESC,EFFSEQ DESC;
SELECT *
FROM ot_uploads_tbl A
WHERE BUCKET_UUID = 'fba500cc1723'
ORDER BY EFFDT DESC,EFFSEQ DESC;
SELECT SYSTIMESTAMP FROM DUAL;

SELECT * FROM EIB_UPLOAD_PROCESS_VW;
SELECT * FROM EIB_SRC_TBL_CONFIG_WORK;
SELECT * FROM TBL_UPD_DYNAMIC_INSERT WHERE  TABLE_NAME LIKE '%EIB_SRC_ORG%' ;
SELECT * FROM TBL_UPD_DYNAMIC_INSERT WHERE PROJECT_ID='2000293' ORDER BY TO_NUMBER(SEQ_ORDER);
SELECT * FROM USER_QUERY WHERE QUERY_NAME='LOAD_EIB_INSERT_2'ORDER BY EFFDT DESC,EFFSEQ DESC;
SELECT * FROM OS_EIB_VALIDATION_SCRIPTS WHERE PROJECT_ID='2000293' AND EFF_STATUS='A';

--LOG TABLES
SELECT * FROM OS_EIB_UPLOAD_LOG WHERE BUCKET_UUID='2952efea56b6';

--VALIDATTION
SELECT * FROM OS_EIB_DATA_ERR WHERE PROJECT_ID='2000433' AND ITERATION_ID='2011000';
--DELETE FROM OS_EIB_DATA_ERR WHERE PROJECT_ID='2000433' AND ITERATION_ID='2011000';
SELECT * FROM OS_EIB_DATA_ERR WHERE PROJECT_ID='2000288' ORDER BY EFFDT DESC ,EFFSEQ DESC;--CONFIG TBL -OS_EIB_VALIDATION_SCRIPTS
SELECT * FROM  OS_EIB_DATA_ERR WHERE PROJECT_ID='2000289' AND ITERATION_ID='1943000'AND MS$MASTERID IN ('20064250','20064255') ORDER BY MS$MASTERID;--AND FILE_NAME='2000291-EIB_SRC_TERM_EMPLOYEE(4).XLSX';

--SRC_TABLE_LIST
SELECT * FROM OS_EIB_SRC_TBLS WHERE  PROJECT_ID='2000363' AND TABLE_NAME NOT IN ('EIB_SRC_CJ_GEN_UNIT_SAL') ORDER BY TO_NUMBER(SRC_ORDER);--100018
SELECT * FROM OS_EIB_SRC_TBLS WHERE PROJECT_ID='2000433' ORDER BY TO_NUMBER(SRC_ORDER);--100007

--FIELD DEFN AND VALIDATION FIELDS CHECK
SELECT COLUMN_NAME,REQUIRED,VALIDATION FROM OS_EIB_SRC_FIELD_DEFN WHERE TABLE_NAME='EIB_SRC_EDIT_WORKER_ADDL_DATA' AND VALIDATION IS NOT NULL;--lessThan90;last90
SELECT COLUMN_NAME,REQUIRED,VALIDATION FROM OS_EIB_SRC_FIELD_DEFN WHERE TABLE_NAME='EIB_SRC_TERM_EMPLOYEE' AND VALIDATION IS NOT NULL;
SELECT * FROM OS_EIB_SRC_FIELD_DEFN WHERE TABLE_NAME='EIB_SRC_REQ_BONUS_MASTER' AND VALIDATION IS NOT NULL;
SELECT * FROM OS_EIB_SRC_FIELD_DEFN WHERE VALIDATION LIKE '%isRequired%';

--LOOKUP FIELDS
SELECT * FROM OS_EIB_LOOKUP_TBL WHERE PROJECT_ID='2000293';
SELECT DISTINCT FIELD_NAME FROM OS_EIB_LOOKUP_TBL WHERE PROJECT_ID='';

--PRIMARY KEY FIELDS CHECK 
SELECT * FROM USER_CONS_COLUMNS WHERE OWNER=USER AND TABLE_NAME='EIB_SRC_CREATE_POSITION_DTL';

SELECT * FROM TBL_UPD_DYNAMIC_INSERT WHERE PROJECT_ID='2000292' ORDER BY TO_NUMBER(SEQ_ORDER);
SELECT * FROM OS_EIB_VALIDATION_SCRIPTS  WHERE PROJECT_ID='2000286' AND EFF_STATUS='A';
SELECT * FROM OS_EIB_VALIDATION_SCRIPTS  WHERE PROJECT_ID='2000304' AND REC_ID='100068' AND EFF_STATUS='A';
SELECT COLUMN_NAME,REQUIRED,VALIDATION FROM OS_EIB_SRC_FIELD_DEFN WHERE TABLE_NAME='EIB_SRC_EDIT_JOB_REQ_ORG' AND VALIDATION IS NOT NULL;

--DEV TO QA MOVE QUERY
--DELETE FROM EIBQ.TBL_UPD_DYNAMIC_INSERT WHERE PROJECT_ID='2000294';
--INSERT INTO EIBQ.TBL_UPD_DYNAMIC_INSERT SELECT PROJECT_ID, TABLE_NAME, SEQ_ORDER, RUN_QUERY, GROUP_NAME, WORK_QRY, MASTERID_COL_NAME, WORK_TBL_NAME, WORK_TO_W_TBL FROM TBL_UPD_DYNAMIC_INSERT WHERE PROJECT_ID='2000294';
--
--DELETE FROM EIBQ.OS_EIB_VALIDATION_SCRIPTS WHERE PROJECT_ID='2000294';
--INSERT INTO EIBQ.OS_EIB_VALIDATION_SCRIPTS SELECT * FROM OS_EIB_VALIDATION_SCRIPTS WHERE PROJECT_ID='2000294' AND EFF_STATUS='A';

--QA TO DEV MOVED QUERY
--DELETE FROM TBL_UPD_DYNAMIC_INSERT WHERE PROJECT_ID='2000542';
--INSERT INTO TBL_UPD_DYNAMIC_INSERT SELECT PROJECT_ID, TABLE_NAME, SEQ_ORDER, RUN_QUERY, GROUP_NAME, WORK_QRY, MASTERID_COL_NAME, WORK_TBL_NAME, WORK_TO_W_TBL FROM EIBQ.TBL_UPD_DYNAMIC_INSERT WHERE PROJECT_ID='2000542';

--DELETE FROM OS_EIB_VALIDATION_SCRIPTS WHERE PROJECT_ID='2000542';
--INSERT INTO OS_EIB_VALIDATION_SCRIPTS SELECT * FROM EIBQ.OS_EIB_VALIDATION_SCRIPTS WHERE PROJECT_ID='2000542';


SELECT * FROM OS_EIB_VALIDATION_SCRIPTS;
SELECT * FROM BKP_OS_EIB_VALIDATION_SCRIPTS;

--DROP TABLE BKP_OS_EIB_VALIDATION_SCRIPTS;
--CREATE TABLE BKP_OS_EIB_VALIDATION_SCRIPTS AS SELECT * FROM OS_EIB_VALIDATION_SCRIPTS;

SELECT * FROM BKP_TBL_UPD_DYNAMIC_INSERT;
--DROP TABLE BKP_TBL_UPD_DYNAMIC_INSERT;
--CREATE TABLE BKP_TBL_UPD_DYNAMIC_INSERT AS SELECT * FROM TBL_UPD_DYNAMIC_INSERT;