--SET SERVEROUTPUT ON;
DECLARE
TBL_NAME VARCHAR2(100):='EIB_SRC_EXT_LEAVE_OF_ABSENCE';
TOP_STK CLOB;
BEGIN 
    FOR A IN (SELECT A.TABLE_NAME,LISTAGG(B.COLUMN_NAME||' = A.'||B.COLUMN_NAME,' AND ') WITHIN GROUP(ORDER BY TO_NUMBER(B.POSITION)) CONS 
                            FROM USER_CONSTRAINTS A JOIN USER_CONS_COLUMNS B ON A.TABLE_NAME = B.TABLE_NAME AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME AND A.TABLE_NAME=TBL_NAME
                            WHERE A.CONSTRAINT_TYPE = 'P' AND B.COLUMN_NAME NOT IN ('EFFDT','EFFSEQ')
                            GROUP BY A.TABLE_NAME)
          LOOP
            TOP_STK :='SELECT * FROM '||TBL_NAME||' A
WHERE 
A.EFFDT=(SELECT MAX(EFFDT) FROM '||TBL_NAME||' WHERE '||A.CONS||') AND 
A.EFFSEQ=(SELECT MAX(EFFSEQ) FROM ' ||TBL_NAME||' WHERE '||A.CONS||' AND  EFFDT = A.EFFDT) AND 
A.EFF_STATUS = ''A''';
                   
               DBMS_OUTPUT.PUT_LINE(TOP_STK);
          END LOOP;
END;

-----------------------------------------------------------------------------------------------------

--SET SERVEROUTPUT ON;
DECLARE
--TBL_NAME VARCHAR2(100):='EIB_SRC_EXT_LEAVE_OF_ABSENCE';
TOP_STK CLOB;
BEGIN 
    FOR A IN (SELECT A.TABLE_NAME,LISTAGG(B.COLUMN_NAME||' = A.'||B.COLUMN_NAME,' AND ') WITHIN GROUP(ORDER BY TO_NUMBER(B.POSITION)) CONS 
                            FROM USER_CONSTRAINTS A JOIN USER_CONS_COLUMNS B ON A.TABLE_NAME = B.TABLE_NAME AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME AND A.TABLE_NAME='EIB_SRC_TERM_REH_ELIG'
                            WHERE A.CONSTRAINT_TYPE = 'P' AND B.COLUMN_NAME NOT IN ('EFFDT','EFFSEQ')
                            GROUP BY A.TABLE_NAME)
          LOOP
            TOP_STK :='SELECT * FROM '||A.TABLE_NAME||' A
WHERE 
A.EFFDT=(SELECT MAX(EFFDT) FROM '||A.TABLE_NAME||' WHERE '||A.CONS||') AND 
A.EFFSEQ=(SELECT MAX(EFFSEQ) FROM ' ||A.TABLE_NAME||' WHERE '||A.CONS||' AND  EFFDT = A.EFFDT) AND 
A.EFF_STATUS = ''A''';
                   
               DBMS_OUTPUT.PUT_LINE(TOP_STK);
          END LOOP;
END;

-----------------------------------------------------------------------------------------------------

--SET SERVEROUTPUT ON;
DECLARE
--TBL_NAME VARCHAR2(100):='EIB_SRC_EXT_LEAVE_OF_ABSENCE';
TOP_STK CLOB;
BEGIN 
    FOR A IN (SELECT A.TABLE_NAME,LISTAGG(B.COLUMN_NAME||' = A.'||B.COLUMN_NAME,' AND ') WITHIN GROUP(ORDER BY TO_NUMBER(B.POSITION)) CONS 
                            FROM 
                            --(SELECT TABLE_NAME TABLE_NAME FROM OS_EIB_SRC_TBLS WHERE PROJECT_ID='2000299') C --NEED TO CHANGES OF TABLE_NAME 
                            (SELECT 'EIB_RAAS_LKP_CONTRACT_DTL' TABLE_NAME FROM DUAL) C
                            JOIN  USER_CONSTRAINTS A ON C.TABLE_NAME=A.TABLE_NAME
                            JOIN USER_CONS_COLUMNS B ON A.TABLE_NAME = B.TABLE_NAME AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME /*AND A.TABLE_NAME=TBL_NAME*/
                            WHERE A.CONSTRAINT_TYPE = 'P' AND B.COLUMN_NAME NOT IN ('EFFDT','EFFSEQ')
                            GROUP BY A.TABLE_NAME)
          LOOP
            TOP_STK :='SELECT * FROM '||A.TABLE_NAME||' A
WHERE 
A.EFFDT=(SELECT MAX(EFFDT) FROM '||A.TABLE_NAME||' WHERE '||A.CONS||') AND 
A.EFFSEQ=(SELECT MAX(EFFSEQ) FROM ' ||A.TABLE_NAME||' WHERE '||A.CONS||' AND  EFFDT = A.EFFDT) AND 
A.EFF_STATUS = ''A''';
                   
               DBMS_OUTPUT.PUT_LINE(TOP_STK||';'||CHR(10));
          END LOOP;
END; 	


WITH CTE_TOP_OF_STACK AS (
SELECT  B.TABLE_NAME,LISTAGG(B.COLUMN_NAME||' =A.'||B.COLUMN_NAME||' AND ') WITHIN GROUP (ORDER BY TO_NUMBER(B.POSITION)) COLUMN_NAME 
    FROM USER_CONSTRAINTS A  
    JOIN USER_CONS_COLUMNS B ON B.TABLE_NAME=A.TABLE_NAME AND B.CONSTRAINT_NAME=A.CONSTRAINT_NAME 
WHERE A.OWNER=USER AND A.CONSTRAINT_TYPE='P'
GROUP BY B.TABLE_NAME)
SELECT TABLE_NAME,COLUMN_NAME,
'SELECT * FROM '||TABLE_NAME||' A WHERE A.EFFDT =(SELECT MAX(EFFDT) FROM '||TABLE_NAME ||' WHERE '
||REPLACE(COLUMN_NAME,'AND EFFDT =A.EFFDT AND EFFSEQ =A.EFFSEQ AND ',')') ||'AND A.EFFSEQ=(SELECT MAX(EFFSEQ) FROM '||TABLE_NAME|| ' WHERE '
||REPLACE (COLUMN_NAME ,'AND EFFSEQ =A.EFFSEQ AND ',')')||'AND A.EFF_STATUS=''A'';'
TOS FROM CTE_TOP_OF_STACK;


WITH CTE_TOP_OF_STACK AS (
SELECT  B.TABLE_NAME,LISTAGG(B.COLUMN_NAME||' =A.'||B.COLUMN_NAME||' AND ') WITHIN GROUP (ORDER BY TO_NUMBER(B.POSITION)) COLUMN_NAME ,
LISTAGG(B.COLUMN_NAME,',') WITHIN GROUP (ORDER BY TO_NUMBER(B.POSITION)) COLS
    FROM USER_CONSTRAINTS A  
    JOIN USER_CONS_COLUMNS B ON B.TABLE_NAME=A.TABLE_NAME AND B.CONSTRAINT_NAME=A.CONSTRAINT_NAME 
WHERE A.OWNER=USER AND A.CONSTRAINT_TYPE='P'
GROUP BY B.TABLE_NAME)
SELECT TABLE_NAME,COLUMN_NAME,COLS,
'SELECT * FROM '||TABLE_NAME||' A WHERE 
A.EFFDT =(SELECT MAX(EFFDT) FROM '||TABLE_NAME ||' WHERE '||REPLACE(COLUMN_NAME,'AND EFFDT =A.EFFDT AND EFFSEQ =A.EFFSEQ AND ',' GROUP BY '||REPLACE (COLS,',EFFDT,EFFSEQ',') ')) ||'AND 
A.EFFSEQ=(SELECT MAX(EFFSEQ) FROM '||TABLE_NAME|| ' WHERE '||REPLACE (COLUMN_NAME ,'AND EFFSEQ =A.EFFSEQ AND ','GROUP BY '||REPLACE (COLS,',EFFSEQ',') '))
||'AND A.EFF_STATUS=''A'';'
TOS FROM CTE_TOP_OF_STACK WHERE TABLE_NAME LIKE '%EIB_SRC_CLOSE_POSITION%';


SYS_EXTRACT_UTC(SYSTIMESTAMP) --TO USE DATE FIELDS
TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP))


literal does not match format string-- THIS ERROR MEANS DATE ERROR


192.168.5.133:3000


UPDATE OS_EIB_VALIDATION_SCRIPTS A
SET A.ERROR_MSG = (
    SELECT 'Required Valid Format' || INITCAP(REPLACE(REPLACE(REPLACE(B.ERROR_MSG, 'YYYY-MM-DD', ''), '_', ' '), 'Required valid', ''))
    FROM OS_EIB_VALIDATION_SCRIPTS B
    WHERE B.PROJECT_ID = A.PROJECT_ID AND B.ERR_TYPE=A.ERR_TYPE 
        AND B.ERROR_MSG LIKE '%DATE%'
)
WHERE A.PROJECT_ID = '2000286'
    AND A.ERROR_MSG LIKE '%DATE%';
	
UPDATE EIB_SRC_TERM_EMPLOYEE A
SET A.MS$MODIFIED_BY=(SELECT TRIM(B.MS$MODIFIED_BY) MS$MODIFIED_BY FROM EIB_SRC_TERM_EMPLOYEE B WHERE B.MS$MASTERID=A.MS$MASTERID 
AND B.EMPLOYEE_ID=A.EMPLOYEE_ID AND B.POSITION=A.POSITION AND B.EFFDT=A.EFFDT AND B.EFFSEQ=A.EFFSEQ);
SELECT TRIM(MS$MODIFIED_BY) MS$MODIFIED_BY FROM EIB_SRC_TERM_EMPLOYEE;

----------------------------------------------------------------
-- NVL DYNAMIC------

SELECT 'NVL((SELECT MAX (EFFSEQ) FROM '||A.TABLE_NAME ||' WHERE '||
(SELECT  REPLACE (LISTAGG(COLUMN_NAME||' = A.'||COLUMN_NAME,' AND ') WITHIN GROUP (ORDER BY POSITION),'A.EFFDT','TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP)) 
GROUP BY '||LISTAGG (COLUMN_NAME,',') WITHIN GROUP (ORDER BY POSITION)) COLUMN_NAME
FROM USER_CONS_COLUMNS WHERE OWNER=USER AND TABLE_NAME=A.TABLE_NAME
AND COLUMN_NAME NOT IN ('EFFSEQ') AND POSITION IS NOT NULL GROUP BY TABLE_NAME )
||')+1,1) EFFSEQ,' 

FROM USER_CONSTRAINTS A  
WHERE A.OWNER=USER AND A.CONSTRAINT_TYPE='P' AND A.TABLE_NAME='EFFECTS' GROUP BY A.TABLE_NAME;


----------------------------------------------------------------------------------------

create or replace FUNCTION GET_NVL_TABLE_TOS(TABLENAME NVARCHAR2) RETURN NVARCHAR2 IS
Output_V NVARCHAR2(2000);
BEGIN

SELECT 'NVL((SELECT MAX (EFFSEQ) FROM '||TABLENAME ||' WHERE '||
(SELECT  REPLACE (LISTAGG(COLUMN_NAME||' = A.'||COLUMN_NAME,' AND ') WITHIN GROUP (ORDER BY POSITION),'A.EFFDT','TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP))') COLUMN_NAME
FROM USER_CONS_COLUMNS WHERE OWNER=USER AND TABLE_NAME=TABLENAME
AND COLUMN_NAME NOT IN ('EFFSEQ') AND POSITION IS NOT NULL  GROUP BY TABLE_NAME )
||'GROUP BY '||(SELECT  LISTAGG(COLUMN_NAME,',') WITHIN GROUP (ORDER BY POSITION) COLUMN_NAME
FROM USER_CONS_COLUMNS WHERE OWNER=USER AND TABLE_NAME=TABLENAME
AND COLUMN_NAME NOT IN ('EFFSEQ') AND POSITION IS NOT NULL  GROUP BY TABLE_NAME )||')+1,1) EFFSEQ,' 

INTO Output_V  FROM USER_CONSTRAINTS A  
WHERE A.OWNER=USER AND A.CONSTRAINT_TYPE='P' AND A.TABLE_NAME=TABLENAME ;
RETURN Output_V;
END;

------------------------------------------------------------------------------------------------------------------

SELECT 'SELECT NVL((SELECT MAX (EFFSEQ) FROM '||A.TABLE_NAME ||' WHERE '||
(SELECT  REPLACE (LISTAGG(COLUMN_NAME||' = A.'||COLUMN_NAME,' AND ') WITHIN GROUP (ORDER BY POSITION),'A.EFFDT','TRUNC(SYS_EXTRACT_UTC(SYSTIMESTAMP))') COLUMN_NAME
FROM USER_CONS_COLUMNS WHERE OWNER=USER AND TABLE_NAME=A.TABLE_NAME AND COLUMN_NAME NOT IN ('EFFSEQ') GROUP BY TABLE_NAME )
||'GROUP BY '||(SELECT  LISTAGG(COLUMN_NAME,',') WITHIN GROUP (ORDER BY POSITION) COLUMN_NAME
FROM USER_CONS_COLUMNS WHERE OWNER=USER AND TABLE_NAME=A.TABLE_NAME
AND COLUMN_NAME NOT IN ('EFFSEQ') GROUP BY TABLE_NAME )||')+1,1) EFFSEQ FROM '||A.TABLE_NAME||' A 
WHERE 
A.EFFDT = (SELECT MAX (EFFDT) FROM '||A.TABLE_NAME ||' WHERE '
||(SELECT  LISTAGG(COLUMN_NAME||' = A.'||COLUMN_NAME,' AND ') WITHIN GROUP (ORDER BY POSITION)||' GROUP BY '||LISTAGG(COLUMN_NAME,',') WITHIN GROUP (ORDER BY POSITION) COLUMN_NAME
FROM USER_CONS_COLUMNS WHERE OWNER=USER AND TABLE_NAME='EFFECTS' AND COLUMN_NAME NOT IN ('EFFDT','EFFSEQ') GROUP BY TABLE_NAME ) ||''

FROM USER_CONSTRAINTS A  
WHERE A.OWNER=USER AND A.CONSTRAINT_TYPE='P' AND A.TABLE_NAME='EFFECTS' ;